services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'promobit'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3316:3306'
    expose:
      - '3316'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: